version = 0.1
[default.deploy.parameters]
stack_name = "temp-kyle-wagner"
resolve_s3 = true
s3_prefix = "temp-kyle-wagner"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
