AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'

  HelloWorldFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'app.handler'
      Runtime: 'python3.12'
      CodeUri: './'
